@host = http://localhost:3000

### Tune creation

# @name createTune
POST {{host}}/tunes
Content-Type: application/json

< ./fixtures/tune.json

### Tune listing -- sortBy ignored (< v1.2>

GET {{host}}/tunes?sortBy=title
Accept-Version: 1.0

### Tune listing -- sortBy used (v1.2+>

GET {{host}}/tunes?sortBy=title
Accept-Version: ^1.2

### Vote on tune

POST {{host}}/tunes/{{createTune.response.headers.X-Tune-ID}}/votes
Content-Type: application/json

{
  "comment": "This tune rocks!",
  "offset": 1
}
